[project]
name = "fastapi-integration"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = "==3.13.*"
dependencies = [
    "aiokafka[lz4]>=0.12",
    "fastapi[all]~=0.118",
    "faststream[kafka]~=0.5",
]
